image: node:carbon

definitions:
  steps:

    - step: &Audit-Step
        name: Audit NPM vulnerabilities
        image:
          name: oltregistry.azurecr.io/tools/npm-audit-ci:latest
          username: $REGISTRY_USER
          password: $REGISTRY_PASSWORD
        script:
          - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          - npm install
          - /app/bin/npm-audit-ci -m
        caches:
          - node

pipelines:

  default:
    - step: *Audit-Step
    - step:
        name: Test
        script:
          - npm install
          - npm run lint
          - npm run test
        caches:
          - node
    - step:
        name: License report
        script:
          - npm install
          - npm run license-report
        caches:
          - node
    - step:
        name: Build documentation
        script:
          - npm install
          - npm run documentation
        caches:
          - node
    - step:
        name: Build
        script:
          - npm install
          - npm run build
        caches:
          - node
  branches:
    master:
      - step: *Audit-Step
      - step:
          name: Build documentation
          script:
            - export DOCKER_IMAGE_TAG=$DOCKER_REPO/${APP_NAME}:${BITBUCKET_BRANCH}_${BITBUCKET_BUILD_NUMBER}
            - npm install
            - npm run documentation
            - docker build -t ${DOCKER_IMAGE_TAG} .
            - docker login -u $DOCKER_REPO_NAME -p $DOCKER_REPO_PASSWORD $DOCKER_REPO
            - docker push ${DOCKER_IMAGE_TAG}
          services:
            - docker
          caches:
            - docker
            - node
